
services:
  web1:
    build:
      context: ./P4-mmnuria-apache
      dockerfile: DockerFileApacheP4
    image: mmnuria-apache-image:p4
    container_name: web1
    volumes:
      - ./web_mmnuria:/var/www/html
      - ./P4-mmnuria-certificados:/etc/apache2/ssl/
    networks:
      red_web:
        ipv4_address: 192.168.10.2
      red_servicios:
        ipv4_address: 192.168.20.2
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  web2:
    image: mmnuria-apache-image:p4
    container_name: web2
    volumes:
      - ./web_mmnuria:/var/www/html
      - ./P4-mmnuria-certificados:/etc/apache2/ssl/
    networks:
      red_web:
        ipv4_address: 192.168.10.3
      red_servicios:
        ipv4_address: 192.168.20.3
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  web3:
    image: mmnuria-apache-image:p4
    container_name: web3
    volumes:
      - ./web_mmnuria:/var/www/html
      - ./P4-mmnuria-certificados:/etc/apache2/ssl/
    networks:
      red_web:
        ipv4_address: 192.168.10.4
      red_servicios:
        ipv4_address: 192.168.20.4
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  web4:
    image: mmnuria-apache-image:p4
    container_name: web4
    volumes:
      - ./web_mmnuria:/var/www/html
      - ./P4-mmnuria-certificados:/etc/apache2/ssl/
    networks:
      red_web:
        ipv4_address: 192.168.10.5
      red_servicios:
        ipv4_address: 192.168.20.5
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  web5:
    image: mmnuria-apache-image:p4
    container_name: web5
    volumes:
      - ./web_mmnuria:/var/www/html
      - ./P4-mmnuria-certificados:/etc/apache2/ssl/
    networks:
      red_web:
        ipv4_address: 192.168.10.6
      red_servicios:
        ipv4_address: 192.168.20.6
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  web6:
    image: mmnuria-apache-image:p4
    container_name: web6
    volumes:
      - ./web_mmnuria:/var/www/html
      - ./P4-mmnuria-certificados:/etc/apache2/ssl/
    networks:
      red_web:
        ipv4_address: 192.168.10.7
      red_servicios:
        ipv4_address: 192.168.20.7
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  web7:
    image: mmnuria-apache-image:p4
    container_name: web7
    volumes:
      - ./web_mmnuria:/var/www/html
      - ./P4-mmnuria-certificados:/etc/apache2/ssl/
    networks:
      red_web:
        ipv4_address: 192.168.10.8
      red_servicios:
        ipv4_address: 192.168.20.8
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  web8:
    image: mmnuria-apache-image:p4
    container_name: web8
    volumes:
      - ./web_mmnuria:/var/www/html
      - ./P4-mmnuria-certificados:/etc/apache2/ssl/
    networks:
      red_web:
        ipv4_address: 192.168.10.9
      red_servicios:
        ipv4_address: 192.168.20.9
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
# Balanceador
  nginx-ssl:
    build:
      context: ./P4-mmnuria-nginx
      dockerfile: DockerFileNginxP4
    image: mmnuria-nginx-image:p4
    container_name: balanceador-nginx-ssl
    volumes:
      - ./P4-mmnuria-certificados:/etc/nginx/ssl/
      - ./P4-mmnuria-nginx/mmnuria-nginx-ssl.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
      - web3
      - web4
      - web5
      - web6
      - web7
      - web8
    ports:
      - "8096:80"
      - "8097:443"
    networks:
      red_web:
        ipv4_address: 192.168.10.50

networks:
  red_web:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
  red_servicios:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
