apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-apache-3
  template:
    metadata:
      labels:
        app: php-apache-3
    spec:
      containers:
      - name: php-apache-3
        image: sufianembark/sufianembark-apache:p1
        ports:
        - containerPort: 80

